
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5000
    onOpen: open-browser
    visibility: private
tasks:
  - init: pipenv install --dev

vscode:
  extensions:
    - ms-python.python
    - yzhang.markdown-all-in-one
    - eamodio.gitlens
    - ahmadawais.shades-of-purple
